### PR TITLE
fetch balance via `fetch` to avoid needing api connection

### LINKED ISSUE #39: Fetching Balance can fail if api is connected to wrong provider
There is a small delay when switching networks

### LINKED ISSUE #44: Click "Send Tokens" without having network added does nothing
And show this error in the console instead

```
_app-781dc87f3e58a1b3.js:28 Uncaught (in promise) {code: 4902, message: 'Unrecognized chain ID "0xbb9". Try adding the chain using wallet_addEthereumChain first.', stack: '{\n  "code": 4902,\n  "message": "Unrecognized chain…fbeogaeaoehlefnkodbefgpgknn/common-1.js:1:185353)'}
```

### PR DESCRIPTION
**Pull request by aidan-starke**
## Description

 - closes #39
 - closes #44
 - fetch balance via `fetch` to avoid needing api connection

### CODE REVIEW

File: libs/utils/ensureEthereumChain.ts [hunk 1]
```diff
@@ -10,8 +10,29 @@ export default async function ensureEthereumChain(
...
-		params: [{ chainId: NETWORKS[network].chainId }],
-	});
+	try {
+		await extension.request({
+			method: "wallet_switchEthereumChain",
+			params: [{ chainId: NETWORKS[network].chainId }],
+		});
+	} catch (error) {
+		if (error.code === 4902) {
+			await extension.request({
```
Comment (ken-futureverse) [inline libs/utils/ensureEthereumChain.ts]: i think there is a function called `addCENNZnetToMetaMask` can we use it instead? might need to update that method so it accepts the `extension` similar to the `ensureEthereumChain`

**Review by ken-futureverse — COMMENTED** [review]
not sure we need to have a locked state (disable the submit button) to wait for network switching, can we just immediately set into `in-progress` mode then then do the network switching / adding. And if adding takes a bit longer, we can just do a `waitUntil` right after the `method: "wallet_addEthereumChain"`

**Comment by aidan-starke** [comment]
> not sure we need to have a locked state (disable the submit button) to wait for network switching, can we just immediately set into `in-progress` mode then then do the network switching / adding. And if adding takes a bit longer, we can just do a `waitUntil` right after the `method: "wallet_addEthereumChain"`

I tried
```
if (!isCorrectApiProvider(api, network)) {
	await waitUntil(3000);
	return onFormSubmit();
}
```

But it just gets stuck in a loop - api & network are both dependencies of the `onFormSubmit` callback

The issue isn't waiting for metamask to switch networks, it's waiting for api to restart with the correct provider - we need this to fetch balances via CENNZnet api - https://github.com/cennznet/app-faucet/blob/hotfix/ensure-correct-provider/libs/hooks/useBalance.ts#L19-L29

**Review by ken-futureverse — COMMENTED** [review]
Okay, as discussed @aidan-starke, we might be overcomplicating a little bit here.

To resolve #44, the following change in `ensureEthereumChain.ts` should do the trick

```typescript
export default async function ensureEthereumChain(
	extension: MetaMaskInpageProvider,
	network: CENNZnetNetwork
): Promise<void> {
	const ethChainId = await extension.request({ method: "eth_chainId" });

	if (ethChainId === NETWORKS[network].chainId) return;

	try {
		await extension.request({
			method: "wallet_switchEthereumChain",
			params: [{ chainId: NETWORKS[network].chainId }],
		});
	} catch (error) {
		if (error?.code !== 4902) throw error;
		await addCENNZnetToMetaMask(network);
	}
}
```

And we don't need to instantiate the API just to query the balance, we can simply create a `fetchCENNZnetBalance` function that query the `genericAsset_getBalance` RPC method as per the example below

```js
fetch("https://nikau.centrality.me/public", {
			method: "POST",
			body: JSON.stringify({
				id: 1,
				jsonrpc: "2.0",
				method: "genericAsset_getBalance",
				params: ["5DJTrWDe5vbs1aB9GWTX93SAz99SkC21KK8L2zfYU6LFpJYJ", 16000],
			}),
			headers: {
				"Content-Type": "application/json",
			},
		})
			.then((response) => response.json())
			.then((response) => console.log(response));
```

So yeah, up to you edit this PR to only have these changes or start a new PR

File: libs/utils/addCENNZnetToMetaMask.ts [hunk 2]
```diff
@@ -1,21 +1,34 @@
...
+			params: [{ chainId: NETWORKS[network].chainId }],
+		});
+	} catch (error) {
+		if (error.code === 4902) {
+			await extension.request({
+				method: "wallet_addEthereumChain",
+				params: [
+					{
+						chainId: NETWORKS[network].chainId,
+						blockExplorerUrls: ["https://uncoverexplorer.com"],
```
Comment (ken-futureverse) [inline libs/utils/addCENNZnetToMetaMask.ts]: can you update to use `nikau.uncoverexplorer.com` and `rata.uncoverexplorer.com`

File: libs/utils/addCENNZnetToMetaMask.ts [hunk 3]
```diff
@@ -1,21 +1,34 @@
...
+	extension: MetaMaskInpageProvider,
+	network: CENNZnetNetwork
+) {
+	try {
+		await extension.request({
+			method: "wallet_switchEthereumChain",
+			params: [{ chainId: NETWORKS[network].chainId }],
+		});
+	} catch (error) {
+		if (error.code === 4902) {
```
Comment (ken-futureverse) [inline libs/utils/addCENNZnetToMetaMask.ts]: need to re-throw other error here, otherwise everything will be silenced.

should be `if(error?.code !== 4902) throw error;` then you can have the `4902` error handler be outside of the if block

**Review by ken-futureverse — CHANGES_REQUESTED** [review]

**Review by ken-futureverse — APPROVED** [review]
